# Makefile for the CS:APP Shell Lab

VERSION = 1
LSH = ./labsh
CC = gcc
CFLAGS = -Wall -O2
FILES = ./labsh 

all: $(FILES)

##################
# Regression tests
##################

# clean up
clean:
	rm -f $(FILES) *.o *~ redirected_file


